In [2]:
import numpy as np 
import pandas as pd

In [3]:
fire_path = "../data/CAL_FIRE_Wildland_PublicReport_2000to2018.csv"
vf_path   = "../data/coccidioidomycosis_m2000_2015_v0.1.csv"

In [4]:
from data_loader import combine_vf_wildfire_data

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [ ]:
county_name = "Fresno"
vf_fire_data = combine_vf_wildfire_data(fire_path=fire_path, vf_cases_path=vf_path, county_name=county_name)

/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py:23: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fire_monthly = fire_county.resample("M").size()
/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py:24: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  all_months = pd.date_range("2006-01-01", "2018-12-31", freq="M")

In [ ]:
vf_fire_data.head()

     Month  Fire Incident Count  VF Case Count
0  2006-01                    0             52
1  2006-02                    0             54
2  2006-03                    0             35
3  2006-04                    0             79
4  2006-05                    0             36

In [ ]:
vf_fire_data.tail()

       Month  Fire Incident Count  VF Case Count
115  2015-08                   47             25
116  2015-09                   37             27
117  2015-10                   16             52
118  2015-11                    9             25
119  2015-12                    5             20

# Create the population data

In [7]:
pop2000_2010_path = "../data/cali_county_pop_2000_2010.csv"
pop2010_2020_path = "../data/cali_county_pop_2010_2020.csv" 

pop1 = pd.read_csv(pop2000_2010_path, header=0)
pop1.head()
pop1c = pop1.copy()
pop1c = pop1c.drop(index=pop1c.index[0])
pop1c.head()

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
1,.Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539","1,513,952"
2,.Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197","1,163"
3,.Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238","38,042"
4,.Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777","220,072"
5,.Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900","45,490"

In [8]:
def clean_pop_dataframe(pop_data_path: str) -> pd.DataFrame:
  raw_data = pd.read_csv(pop_data_path)
  data_clean = raw_data.copy()
  data_clean = data_clean.drop(index=data_clean.index[0])
  data_clean['Geographic Area'] = data_clean['Geographic Area'].str.strip().str.replace(".", "", regex=False)
  return data_clean

In [9]:
pop1 = clean_pop_dataframe(pop2000_2010_path)
pop1.head()

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
1,Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539","1,513,952"
2,Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197","1,163"
3,Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238","38,042"
4,Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777","220,072"
5,Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900","45,490"

In [10]:
pop2 = clean_pop_dataframe(pop2010_2020_path)
pop2.head()

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,"Alameda County, California","1,513,413","1,532,981","1,557,493","1,584,943","1,614,744","1,643,103","1,661,218","1,671,949","1,680,392","1,683,879","1,682,370"
2,"Alpine County, California","1,164","1,105","1,132","1,160","1,122","1,128","1,110","1,183","1,157","1,198","1,202"
3,"Amador County, California","37,893","37,593","37,201","36,763","36,916","37,263","37,711","38,859","39,702","40,089","40,473"
4,"Butte County, California","219,883","219,639","220,257","220,755","222,355","223,198","224,502","226,704","228,059","216,181","211,631"
5,"Calaveras County, California","45,442","45,033","44,588","44,328","44,246","44,440","44,674","44,923","44,911","45,181","45,282"

In [ ]:
from data_loader import *

In [ ]:
from data_loader import clean_pop_dataframe2

ImportError: cannot import name 'clean_pop_dataframe2' from 'data_loader' (/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py)

In [ ]:
from data_loader import clean_pop_dataframe
pop1 = clean_pop_dataframe("../data/cali_county_pop_2000_2010.csv")
pop1.head()

ImportError: cannot import name 'clean_pop_dataframe' from 'data_loader' (/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py)

In [5]:
def clean_pop_dataframe(pop_data_path: str) -> pd.DataFrame:
    raw_data = pd.read_csv(pop_data_path)
    data_clean = raw_data.copy()
    data_clean = data_clean.drop(index=data_clean.index[0])# From current pop data, this is the row that just states the overall california population data, not useful for our cases right now
    data_clean['Geographic Area'] = data_clean['Geographic Area'].str.strip().str.replace(".", "", regex=False).str.replace(", California", "", regex=False) # Current first column values have a . before county name, i.e .Fresno
    return data_clean

In [6]:
pop1 = clean_pop_dataframe(pop2000_2010_path)
pop1.head()

NameError: name 'pop2000_2010_path' is not defined

In [11]:
pop2 = clean_pop_dataframe(pop2010_2020_path)
pop2.head()

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,"Alameda County, California","1,513,413","1,532,981","1,557,493","1,584,943","1,614,744","1,643,103","1,661,218","1,671,949","1,680,392","1,683,879","1,682,370"
2,"Alpine County, California","1,164","1,105","1,132","1,160","1,122","1,128","1,110","1,183","1,157","1,198","1,202"
3,"Amador County, California","37,893","37,593","37,201","36,763","36,916","37,263","37,711","38,859","39,702","40,089","40,473"
4,"Butte County, California","219,883","219,639","220,257","220,755","222,355","223,198","224,502","226,704","228,059","216,181","211,631"
5,"Calaveras County, California","45,442","45,033","44,588","44,328","44,246","44,440","44,674","44,923","44,911","45,181","45,282"

In [12]:
pop1_2010_drop = pop1.drop(columns=['2010'])
pop1_2010_drop.head()

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
1,Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539"
2,Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197"
3,Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238"
4,Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777"
5,Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900"

In [ ]:
pop_comb = pop1_2010_drop.join(pop2, how='inner')

ValueError: columns overlap but no suffix specified: Index(['Geographic Area'], dtype='object')

In [17]:
pop1_2010_drop = pop1_2010_drop.set_index("Geographic Area")
pop2 = pop2.set_index("Geographic Area")

pop_comb = pop1_2010_drop.join(pop2, how="inner")

KeyError: "None of ['Geographic Area'] are in the columns"

In [14]:
pop_comb.head()

Empty DataFrame
Columns: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
Index: []

[0 rows x 21 columns]

In [15]:
pop_comb.iloc[0]

IndexError: single positional indexer is out-of-bounds

In [16]:
pop_comb.loc["Fresno County"]

KeyError: 'Fresno County'

In [ ]:
start_year = "2006"

In [ ]:
print(int(start_year))

2006

In [22]:
import pandas as pd 
def grab_specific_county_data(df: pd.DataFrame, county_name: str, start_year: str, end_year: str) -> pd.Series:
    """
    Grab_Specific_County_Data: This function reports back the population data 
    for a given county over a specified year span (from 2000 to 2020 max)
    
    Inputs:
        - df: Dataframe of the (combined, hopefully) population datasets. 
              Doesn't actually need to be, to be honest
        - county_name: Name of the county to pull data for
        - start_year: starting year for the query, as a string
        - end_year: ending year of the query, as a string
    
    Outputs:
        - queried_data: pd.Series object with the population data for 
                        that given county from the specified year range
    """

    year_cols = df.columns.astype(str)
    if start_year not in year_cols or end_year not in year_cols:
        raise ValueError(f"Start year {start_year} or End year {end_year} are out of bounds")
    
    if county_name not in df.index:
        raise ValueError(f"County Name {county_name} not in Population Data")
    
        return df.loc[county_name, start_year:end_year]

In [23]:
pop1_path = "../data/cali_county_pop_2000_2010.csv" 
pop2_path = "../data/cali_county_pop_2010_2020.csv"

In [24]:
from data_loader import combine_pop_datasets

In [25]:
pop_combined = combine_pop_datasets(pop1_path, pop2_path, True)

In [26]:
pop_combined.head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Geographic Area,,,,,,,,,,,,,,,,,,,,,
Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539",...,"1,532,981","1,557,493","1,584,943","1,614,744","1,643,103","1,661,218","1,671,949","1,680,392","1,683,879","1,682,370"
Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197",...,"1,105","1,132","1,160","1,122","1,128","1,110","1,183","1,157","1,198","1,202"
Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238",...,"37,593","37,201","36,763","36,916","37,263","37,711","38,859","39,702","40,089","40,473"
Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777",...,"219,639","220,257","220,755","222,355","223,198","224,502","226,704","228,059","216,181","211,631"
Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900",...,"45,033","44,588","44,328","44,246","44,440","44,674","44,923","44,911","45,181","45,282"

In [27]:
from data_loader import grab_specific_county_data

fresno_data = grab_specific_county_data(pop_combined, "Fresno County", "2006", "2015")

In [28]:
fresno_data.head()

2006    883,862
2007    895,933
2008    909,630
2009    921,478
2010    932,202
Name: Fresno County, dtype: object

In [29]:
print(fresno_data)

2006    883,862
2007    895,933
2008    909,630
2009    921,478
2010    932,202
2011    940,206
2012    946,501
2013    953,630
2014    963,323
2015    972,906
Name: Fresno County, dtype: object

# Pop Data Results Altogether so far
Doing this to ignore whatever errors were above, too lazy to clean up this notebook

In [60]:
import pandas as pd 
from data_loader import combine_pop_datasets, grab_specific_county_data, combine_vf_wildfire_data
pop1_path = '../data/cali_county_pop_2000_2010.csv' 
pop2_path = '../data/cali_county_pop_2010_2020.csv'
vf_cases_path = '../data/coccidioidomycosis_m2000_2015_v0.1.csv'
wildfire_path = '../data/CAL_FIRE_Wildland_PublicReport_2000to2018.csv'

county = "Fresno"
county_name = county + " " + "County" # this is for the pop data
start_year = "2006" 
end_year   = "2015"

vf_fire_comb = combine_vf_wildfire_data(wildfire_path, vf_cases_path, county)

pop_data_comb = combine_pop_datasets(pop1_path, pop2_path, True)

tgt_pop_data = grab_specific_county_data(pop_data_comb, county_name, start_year, end_year)

/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py:23: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fire_monthly = fire_county.resample("M").size()
/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py:24: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  all_months = pd.date_range("2006-01-01", "2018-12-31", freq="M")

In [61]:
print(tgt_pop_data)
pop_vals = tgt_pop_data
pop_vals = pop_vals.str.replace(",","").astype(int)
pop_vals

2006    883,862
2007    895,933
2008    909,630
2009    921,478
2010    932,202
2011    940,206
2012    946,501
2013    953,630
2014    963,323
2015    972,906
Name: Fresno County, dtype: object

2006    883862
2007    895933
2008    909630
2009    921478
2010    932202
2011    940206
2012    946501
2013    953630
2014    963323
2015    972906
Name: Fresno County, dtype: int64

# Potential Strategies


We need to make sure the population data is the same size as the fire data and case data. The pop data is only given once a year, so we have two possible approaches (maybe more?):

1. Copy the pop data for that year 12 times for each year (like 2006-01 to 2015-12).
2. Use linear interpolation to project the data per each month

In [62]:
def expand_yearly_to_monthly(pop_series: pd.Series, monthly_index: pd.DatetimeIndex) -> pd.Series:
    # Ensure population index is int (e.g., 2006, 2007...)
    pop_series.index = pop_series.index.astype(int)

    # Create a Series with monthly datetime index and values repeated per year
    monthly_pop = pd.Series(index=monthly_index, dtype=int)

    for date in monthly_index:
        year = date.year
        if year in pop_series.index:
            monthly_pop[date] = pop_series[year]
        else:
            raise ValueError(f"Missing population data for year {year}")

    return monthly_pop

In [65]:
vf_fire_comb1 = vf_fire_comb.copy()
print(vf_fire_comb1)

       Month  Fire Incident Count  VF Case Count
0    2006-01                    0             52
1    2006-02                    0             54
2    2006-03                    0             35
3    2006-04                    0             79
4    2006-05                    0             36
..       ...                  ...            ...
115  2015-08                   47             25
116  2015-09                   37             27
117  2015-10                   16             52
118  2015-11                    9             25
119  2015-12                    5             20

[120 rows x 3 columns]

In [66]:
vf_fire_comb1 = vf_fire_comb1.set_index('Month')

In [52]:
vf_fire_comb1.index = pd.to_datetime(vf_fire_comb1.index)

In [55]:
vf_fire_comb1

         Fire Incident Count  VF Case Count
Month
2006-01                    0             52
2006-02                    0             54
2006-03                    0             35
2006-04                    0             79
2006-05                    0             36
...                      ...            ...
2015-08                   47             25
2015-09                   37             27
2015-10                   16             52
2015-11                    9             25
2015-12                    5             20

[120 rows x 2 columns]

In [69]:
vf_fire_comb1.index = pd.to_datetime(vf_fire_comb1.index)

In [70]:
vf_fire_comb1

            Fire Incident Count  VF Case Count
Month
2006-01-01                    0             52
2006-02-01                    0             54
2006-03-01                    0             35
2006-04-01                    0             79
2006-05-01                    0             36
...                         ...            ...
2015-08-01                   47             25
2015-09-01                   37             27
2015-10-01                   16             52
2015-11-01                    9             25
2015-12-01                    5             20

[120 rows x 2 columns]

In [72]:
tgt_pop_data = tgt_pop_data.str.replace(",","").astype(int)

In [73]:
tgt_pop_data

2006    883862
2007    895933
2008    909630
2009    921478
2010    932202
2011    940206
2012    946501
2013    953630
2014    963323
2015    972906
Name: Fresno County, dtype: int64

In [74]:
tgt_pop_data.index = tgt_pop_data.index.astype(int)

In [75]:
tgt_pop_data

2006    883862
2007    895933
2008    909630
2009    921478
2010    932202
2011    940206
2012    946501
2013    953630
2014    963323
2015    972906
Name: Fresno County, dtype: int64

In [ ]:
vf_fire_comb1["Population"] = vf_fire_comb1.index.year.map()