In [37]:
import numpy as np 
import pandas as pd

In [38]:
fire_path = "../data/CAL_FIRE_Wildland_PublicReport_2000to2018.csv"
vf_path   = "../data/coccidioidomycosis_m2000_2015_v0.1.csv"

In [39]:
from data_loader import combine_vf_wildfire_data

In [40]:
county_name = "Fresno"
vf_fire_data = combine_vf_wildfire_data(fire_path=fire_path, vf_cases_path=vf_path, county_name=county_name)

/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py:23: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fire_monthly = fire_county.resample("M").size()
/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py:24: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  all_months = pd.date_range("2006-01-01", "2018-12-31", freq="M")

In [41]:
vf_fire_data.head()

     Month  Fire Incident Count  VF Case Count
0  2006-01                    0             52
1  2006-02                    0             54
2  2006-03                    0             35
3  2006-04                    0             79
4  2006-05                    0             36

In [42]:
vf_fire_data.tail()

       Month  Fire Incident Count  VF Case Count
115  2015-08                   47             25
116  2015-09                   37             27
117  2015-10                   16             52
118  2015-11                    9             25
119  2015-12                    5             20

# Create the population data

In [43]:
pop2000_2010_path = "../data/cali_county_pop_2000_2010.csv"
pop2010_2020_path = "../data/cali_county_pop_2010_2020.csv" 

pop1 = pd.read_csv(pop2000_2010_path, header=0)
pop1.head()
pop1c = pop1.copy()
pop1c = pop1c.drop(index=pop1c.index[0])
pop1c.head()

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
1,.Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539","1,513,952"
2,.Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197","1,163"
3,.Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238","38,042"
4,.Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777","220,072"
5,.Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900","45,490"

In [44]:
def clean_pop_dataframe(pop_data_path: str) -> pd.DataFrame:
  raw_data = pd.read_csv(pop_data_path)
  data_clean = raw_data.copy()
  data_clean = data_clean.drop(index=data_clean.index[0])
  data_clean['Geographic Area'] = data_clean['Geographic Area'].str.strip().str.replace(".", "", regex=False)
  return data_clean

In [45]:
pop1 = clean_pop_dataframe(pop2000_2010_path)
pop1.head()

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
1,Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539","1,513,952"
2,Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197","1,163"
3,Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238","38,042"
4,Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777","220,072"
5,Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900","45,490"

In [46]:
pop2 = clean_pop_dataframe(pop2010_2020_path)
pop2.head()

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,"Alameda County, California","1,513,413","1,532,981","1,557,493","1,584,943","1,614,744","1,643,103","1,661,218","1,671,949","1,680,392","1,683,879","1,682,370"
2,"Alpine County, California","1,164","1,105","1,132","1,160","1,122","1,128","1,110","1,183","1,157","1,198","1,202"
3,"Amador County, California","37,893","37,593","37,201","36,763","36,916","37,263","37,711","38,859","39,702","40,089","40,473"
4,"Butte County, California","219,883","219,639","220,257","220,755","222,355","223,198","224,502","226,704","228,059","216,181","211,631"
5,"Calaveras County, California","45,442","45,033","44,588","44,328","44,246","44,440","44,674","44,923","44,911","45,181","45,282"

In [49]:
from data_loader import *

In [52]:
from data_loader import clean_pop_dataframe2

ImportError: cannot import name 'clean_pop_dataframe2' from 'data_loader' (/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py)

In [53]:
from data_loader import clean_pop_dataframe
pop1 = clean_pop_dataframe("../data/cali_county_pop_2000_2010.csv")
pop1.head()

ImportError: cannot import name 'clean_pop_dataframe' from 'data_loader' (/Users/dballen/Documents/GitHub/CSUF-Project-Code/Project/code/data_loader.py)

In [57]:
def clean_pop_dataframe(pop_data_path: str) -> pd.DataFrame:
    raw_data = pd.read_csv(pop_data_path)
    data_clean = raw_data.copy()
    data_clean = data_clean.drop(index=data_clean.index[0])# From current pop data, this is the row that just states the overall california population data, not useful for our cases right now
    data_clean['Geographic Area'] = data_clean['Geographic Area'].str.strip().str.replace(".", "", regex=False).str.replace(", California", "", regex=False) # Current first column values have a . before county name, i.e .Fresno
    return data_clean

In [58]:
pop1 = clean_pop_dataframe(pop2000_2010_path)
pop1.head()

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
1,Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539","1,513,952"
2,Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197","1,163"
3,Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238","38,042"
4,Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777","220,072"
5,Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900","45,490"

In [59]:
pop2 = clean_pop_dataframe(pop2010_2020_path)
pop2.head()

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,Alameda County,"1,513,413","1,532,981","1,557,493","1,584,943","1,614,744","1,643,103","1,661,218","1,671,949","1,680,392","1,683,879","1,682,370"
2,Alpine County,"1,164","1,105","1,132","1,160","1,122","1,128","1,110","1,183","1,157","1,198","1,202"
3,Amador County,"37,893","37,593","37,201","36,763","36,916","37,263","37,711","38,859","39,702","40,089","40,473"
4,Butte County,"219,883","219,639","220,257","220,755","222,355","223,198","224,502","226,704","228,059","216,181","211,631"
5,Calaveras County,"45,442","45,033","44,588","44,328","44,246","44,440","44,674","44,923","44,911","45,181","45,282"

In [63]:
pop1_2010_drop = pop1.drop(columns=['2010'])
pop1_2010_drop.head()

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
1,Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539"
2,Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197"
3,Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238"
4,Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777"
5,Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900"

In [64]:
pop_comb = pop1_2010_drop.join(pop2, how='inner')

ValueError: columns overlap but no suffix specified: Index(['Geographic Area'], dtype='object')

In [65]:
pop1_2010_drop = pop1_2010_drop.set_index("Geographic Area")
pop2 = pop2.set_index("Geographic Area")

pop_comb = pop1_2010_drop.join(pop2, how="inner")

In [66]:
pop_comb.head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Geographic Area,,,,,,,,,,,,,,,,,,,,,
Alameda County,"1,449,840","1,469,484","1,462,106","1,454,163","1,445,721","1,441,545","1,444,484","1,455,715","1,477,208","1,498,539",...,"1,532,981","1,557,493","1,584,943","1,614,744","1,643,103","1,661,218","1,671,949","1,680,392","1,683,879","1,682,370"
Alpine County,"1,209","1,196","1,237","1,233","1,263","1,219","1,276","1,274","1,202","1,197",...,"1,105","1,132","1,160","1,122","1,128","1,110","1,183","1,157","1,198","1,202"
Amador County,"35,153","35,697","36,561","36,994","37,400","38,040","38,353","38,756","38,248","38,238",...,"37,593","37,201","36,763","36,916","37,263","37,711","38,859","39,702","40,089","40,473"
Butte County,"203,807","206,193","209,120","211,481","213,065","214,752","216,824","217,469","219,034","219,777",...,"219,639","220,257","220,755","222,355","223,198","224,502","226,704","228,059","216,181","211,631"
Calaveras County,"40,645","41,304","42,380","43,755","44,530","45,295","46,045","46,268","46,265","45,900",...,"45,033","44,588","44,328","44,246","44,440","44,674","44,923","44,911","45,181","45,282"

In [67]:
pop_comb.iloc[0]

2000    1,449,840
2001    1,469,484
2002    1,462,106
2003    1,454,163
2004    1,445,721
2005    1,441,545
2006    1,444,484
2007    1,455,715
2008    1,477,208
2009    1,498,539
2010    1,513,413
2011    1,532,981
2012    1,557,493
2013    1,584,943
2014    1,614,744
2015    1,643,103
2016    1,661,218
2017    1,671,949
2018    1,680,392
2019    1,683,879
2020    1,682,370
Name: Alameda County, dtype: object

In [68]:
pop_comb.loc["Fresno County"]

2000      801,288
2001      813,021
2002      829,762
2003      847,193
2004      861,035
2005      872,470
2006      883,862
2007      895,933
2008      909,630
2009      921,478
2010      932,202
2011      940,206
2012      946,501
2013      953,630
2014      963,323
2015      972,906
2016      981,015
2017      990,274
2018      997,611
2019    1,004,925
2020    1,008,653
Name: Fresno County, dtype: object